Fix rcgen API: use self_signed() instead of Certificate::from_params()
- Line 42: Changed `Certificate::from_params(ca_params)` to `ca_params.self_signed(&ca_key)`
- Line 69: Changed `Certificate::from_params(params)` to `params.self_signed(&self.ca_key)`
- rcgen 0.13 uses self_signed() method instead of Certificate::from_params()
- Fixes compilation error: no function or associated item named `from_params` found